type Translate = (key: string, fallback: string) => string;
let translate: Translate = (_key, fallback) => fallback;

/** Lets the app localise the messages below without this file importing i18n. */
export const setErrorMessageTranslator = (fn: Translate) => {
    translate = fn;
};

const NETWORK_PATTERN = /network error|network request failed|fetch failed|unknownhost|unable to resolve host|no address associated|enotfound|econnrefused|econnreset|failed to connect|internet connection appears to be offline/i;
const TIMEOUT_PATTERN = /timeout|timed out/i;
const SERVER_DOWN_PATTERN = /status code 50[234]|\b50[234]\b.*(bad gateway|unavailable|gateway timeout)/i;

const messageOf = (error: unknown): string => {
    if (typeof error === 'string') return error;
    const message = (error as any)?.message;
    return typeof message === 'string' ? message : '';
};

/** True when the request never reached the server (offline, DNS, refused). */
export const isNetworkError = (error: unknown): boolean => {
    if ((error as any)?.response) return false;
    return NETWORK_PATTERN.test(messageOf(error));
};

/** Plain-language text for transport-level failures, or null for anything else. */
const describeTransportFailure = (error: unknown): string | null => {
    const status = (error as any)?.response?.status;
    const message = messageOf(error);
    if (isNetworkError(error)) {
        return translate('errors.offline', 'No internet connection. Check your network and try again.');
    }
    if (status === 502 || status === 503 || status === 504 || SERVER_DOWN_PATTERN.test(message)) {
        return translate('errors.serverUnavailable', 'The server is temporarily unavailable. Your notes are safe; try again in a minute.');
    }
    if (!(error as any)?.response && TIMEOUT_PATTERN.test(message) && !/\{/.test(message)) {
        return translate('errors.timeout', 'The request took too long. Check your connection and try again.');
    }
    return null;
};

export const getErrorMessage = (error: unknown, fallback = 'Something went wrong'): string => {
    const transport = describeTransportFailure(error);
    if (transport) return transport;

    if (typeof error === 'string') {
        // Check if error matches any specific patterns
        const parsed = parseStringError(error);
        // If parsed is same as error and we have a custom fallback that isn't default, maybe we should return fallback?
        // But parseStringError is designed to clean up the string. If it can't, it returns it.
        // Original logic passed fallback to parseStringError which ignored it.
        return parsed;
    }

    if (error && typeof error === 'object') {
        const maybeError = error as any;

        // generated by axios or similar
        const detail = maybeError?.response?.data?.detail;
        if (typeof detail === 'string' && detail.trim().length > 0) {
            return detail;
        }

        // generated by our AIService or standard Error
        if (typeof maybeError?.message === 'string' && maybeError.message.trim().length > 0) {
            return parseStringError(maybeError.message);
        }
    }

    return fallback;
};

const parseStringError = (msg: string): string => {
    // Check for "API Error: STATUS - JSON" format from AIService
    // Example: "API Error: 401 - { ... }"
    // or just raw JSON

    let jsonPart = msg;
    const jsonStart = msg.indexOf('{');
    const jsonEnd = msg.lastIndexOf('}');

    if (jsonStart !== -1 && jsonEnd !== -1 && jsonEnd > jsonStart) {
        jsonPart = msg.substring(jsonStart, jsonEnd + 1);
        try {
            const parsed = JSON.parse(jsonPart);

            // OpenAI Format: { "error": { "message": "...", "type": "...", ... } }
            if (parsed.error && parsed.error.message) {
                // Check for specific OpenAI keywords to make them friendlier
                if (parsed.error.code === 'insufficient_quota' || parsed.error.message.includes('quota')) {
                    return 'You have run out of credits or your trial has expired. Please check your plan.';
                }
                if (parsed.error.code === 'invalid_api_key' || parsed.error.message.includes('API key')) {
                    return 'The provided API Key is invalid. Please check your settings.';
                }
                return parsed.error.message;
            }

            // Common Backend Format: { "detail": "..." } or { "message": "..." }
            if (parsed.detail) return parsed.detail;
            if (parsed.message) return parsed.message;
            if (parsed.error) return parsed.error; // simpler format

        } catch (e) {
            // parsing failed, use original message but maybe clean it up?
            // If it starts with "API Error: ...", we might want to just show "Server Error" + status if we can't parse contents.
            // But for now, let's fall back to returning the full string if we can't parse it, 
            // OR if the user wants "Beautiful errors", maybe we shouldn't show raw JSON.
        }
    }

    // If we have a status code indicator but no clear JSON, clean it up
    if (msg.includes('API Error:')) {
        if (msg.includes('503') || msg.includes('ngrok')) {
            return 'Agent service is temporarily unavailable (Server 503). Your note is safe.';
        }
        // e.g. "API Error: 500 - Internal Server Error"
        return msg.replace('API Error:', 'Server Error').trim();
    }

    // Direct checks for ngrok
    if (msg.includes('ngrok') || msg.includes('limit_exceeded')) {
        return 'Server connection limit exceeded. Please try again later.';
    }

    if (msg.trim().toLowerCase() === 'network error') {
        return 'Cannot reach the server. Check internet connection and try again.';
    }

    if (msg.toLowerCase().includes('timeout') && msg.toLowerCase().includes('exceeded')) {
        return 'Request timed out. Please try again.';
    }

    return msg;
};
